### ISSUE TITLE
react-genome-view 2.0.1 with vite

### ISSUE THREAD

**Issue by Manubi** [GMOD/jbrowse-components#3112]
Hi,
just to let you know I wasn't able to make it work with vite. I've spend half a day with the polyfills (util, buffer) that have changed. I don't mind as I can stay on 1.7.2.

**Comment by cmdcolin** [comment]
vite 3.x has an error currently but vite 2.x can work

a fix for vite 3.x was added to our main branch and will be released soon (xref https://github.com/gmod/jbrowse-components/pull/3092)

**Comment by cmdcolin** [comment]
will get fixed in next release :)

**Comment by cmdcolin** [comment]
new release out, should work with vite 3 :)

**Comment by Manubi** [comment]
Hi,
 I still have problems with updating.

"vite": "^3.0.4",
"@jbrowse/react-linear-genome-view": "^2.1.0",
"@esbuild-plugins/node-globals-polyfill": "^0.1.1",
 "@esbuild-plugins/node-modules-polyfill": "^0.1.4",

If I add the `Buffer` to my resolvers like this
<img width="992" alt="CleanShot 2022-08-02 at 11 52 56@2x" src="https://user-images.githubusercontent.com/20935138/182346702-74f5ab37-c9d0-471f-a832-227bb2781947.png">
 It gives me the following error:
<img width="1725" alt="CleanShot 2022-08-02 at 11 53 40@2x" src="https://user-images.githubusercontent.com/20935138/182346823-6dfe3162-e023-4747-8ee0-fa949cabe79b.png">
If I delete the Buffer resolver I'll get the following error.
<img width="1778" alt="CleanShot 2022-08-02 at 11 54 34@2x" src="https://user-images.githubusercontent.com/20935138/182347052-4af5b8e7-f95d-482e-9356-ad03884ba059.png">

Any ideas?

**Comment by cmdcolin** [comment]
might compare against the vite config at https://jbrowse.org/jb2/docs/embedded_components/ (https://github.com/GMOD/jbrowse-components/blob/main/demos/jbrowse-react-linear-genome-view-vite/vite.config.ts)

this example should be working

**Comment by Manubi** [comment]
The config from that example is a little confusing. For example the `stream-browserify` package is not needed as you could import it from the `esbuild` package.
```
stream: "rollup-plugin-node-polyfills/polyfills/stream",
```
  

But back to my issue: The strange thing is, if you compare the images, the `Repeats` and the `Genecode v36` have the same error on the second image. If I add the Buffer the `Repeats` work fine and only the `Genecode v36` will throw an error. Did you maybe change anything with that `Genecode v36` thing? 

Sorry I am not a biologist so don't know that much about the stuff.

**Comment by garrettjstevens** [comment]
I don't think it's an issue with the Gencode 36 track, here it is running using the demo config Colin mentioned:

![localhost_5173_](https://user-images.githubusercontent.com/25592344/182739136-9a69c483-14c6-44f5-9409-21e7b1dd969e.png)

Also, I tried using the stream polyfill from the rollup plugin like you suggested and that seemed to work fine as well.
