### ISSUE TITLE
Yarn upgrade causes errors on master after rescripts merge

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#585]
If "yarn upgrade" is run on master I get this error inside the console.log of jbrowse-web after yarn start

```
Uncaught Error: Module build failed (from /home/cdiesh/src/jbrowse-components/node_modules/babel-loader/lib/index.js):
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js",
    "options": {
      "loaderMap": {
        "svg": {
          "ReactComponent": "@svgr/webpack?-svgo,+titleProp,+ref![path]"
        }
      }
    },
    "dirname": "/home/cdiesh/src/jbrowse-components/packages/jbrowse-web",
    "ownPass": false,
    "file": {
      "request": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js",
      "resolved": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js"
    }
  },
  {
    "alias": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js",
    "options": {
      "loaderMap": {
        "svg": {
          "ReactComponent": "@svgr/webpack?-prettier,-svgo![path]"
        }
      }
    },
    "dirname": "/home/cdiesh/src/jbrowse-components/packages/jbrowse-web",
    "ownPass": false,
    "file": {
      "request": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js",
      "resolved": "/home/cdiesh/src/jbrowse-components/node_modules/babel-plugin-named-asset-import/index.js"
    }
  }
]
    at assertNoDuplicates (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-descriptors.js:206:13)
    at createDescriptors (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-descriptors.js:114:3)
    at createPluginDescriptors (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
    at alias (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-descriptors.js:63:49)
    at cachedFunction (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/caching.js:33:19)
    at plugins.plugins (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-descriptors.js:28:77)
    at mergeChainOpts (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-chain.js:319:26)
    at /home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/config-chain.js:68:29)
    at loadPrivatePartialConfig (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/home/cdiesh/src/jbrowse-components/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/home/cdiesh/src/jbrowse-components/node_modules/babel-loader/lib/index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/cdiesh/src/jbrowse-components/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/home/cdiesh/src/jbrowse-components/node_modules/babel-loader/lib/index.js:5:194)
    at /home/cdiesh/src/jbrowse-components/node_modules/babel-loader/lib/index.js:5:364
    at Object.../../node_modules/babel-loader/lib/index.js?!../../node_modules/babel-loader/lib/index.js?!../../node_modules/eslint-loader/dist/cjs.js?!./src/rpc.worker.js (http://localhost:3000/6c8855188841abc04bdc.worker.js:96:7)
    at __webpack_require__ (http://localhost:3000/6c8855188841abc04bdc.worker.js:20:30)
    at http://localhost:3000/6c8855188841abc04bdc.worker.js:84:18
    at http://localhost:3000/6c8855188841abc04bdc.worker.js:87:10
```

**Comment by cmdcolin** [comment]
```
babel-plugin-named-asset-import@^0.3.0:
  version "0.3.2"
  resolved "https://registry.yarnpkg.com/babel-plugin-named-asset-import/-/babel-plugin-named-asset-import-0.3.2.tgz#20978ed446b8e1bf4a2f42d0a94c0ece85f75f4f"
  integrity sha512-CxwvxrZ9OirpXQ201Ec57OmGhmI8/ui/GwTDy0hSp6CmRvgRC0pSair6Z04Ck+JStA0sMPZzSJ3uE4n17EXpPQ==

babel-plugin-named-asset-import@^0.3.4:
  version "0.3.4"
  resolved "https://registry.yarnpkg.com/babel-plugin-named-asset-import/-/babel-plugin-named-asset-import-0.3.4.tgz#4a8fc30e9a3e2b1f5ed36883386ab2d84e1089bd"
  integrity sha512-S6d+tEzc5Af1tKIMbsf2QirCcPdQ+mKUCY2H1nJj1DyA1ShwpsoxEOAwbWsG5gcXNV/olpvQd9vrUWRx4bnhpw==

```
This appears to fix the issue, it is a specific modification to yarn.lock

**Comment by cmdcolin** [comment]
If those two entries get combined by semver then the problem of "duplicate entries" happens

**Comment by cmdcolin** [comment]
The root cause is likely because of the entry being duplicated and the yarn.lock is just a way to artificially de-duplicate it by referring to two different versions

**Comment by rbuels** [comment]
is this still a thing, or can it be closed

**Comment by cmdcolin** [comment]
Pretty sure this is still an issue and so our yarn.lock carefully maintains this...

**Comment by rbuels** [comment]
any ideas what the solution is?

**Comment by cmdcolin** [comment]
Basically no, the rescripts merger may have Introduced the issue but didn't get clues how to fix

**Comment by cmdcolin** [comment]
Oh it fixed now actually

**Comment by garrettjstevens** [comment]
Wait, really? I just tried it on my computer on master and it's still broken.

**Comment by cmdcolin** [comment]
Oh actually you're right, I looked in the console log and there are issues and the app doesn't fully load. I was deceived by the app partially loading
