### ISSUE TITLE
Alignments tracks launches two independent requests for BAI file with SNP/Pileup combo enabled

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#853]
It appears to be creating two different BamAdapter instances

**Comment by cmdcolin** [comment]
@rbuels would you be able to see if the work you are doing takes into account things like this

there are a number of double downloads of files across different webworkers for these different stages e.g. for SNPCoverage and Pileup there will potentially be getRefNames, getMultiRegionStats, and render

**Comment by rbuels** [comment]
I think this is fixed in master, reopen if you see it again

**Comment by cmdcolin** [comment]
This is not fixed still AFAIK. Opening SKBR3 pacbio (NGMLR) downloads the entire bai file multiple times in the network tab (90MB, pretty noticeable) but it can be seen in volvox too, in volvox it uses , it should not be launching multiple requests for the same bai if it is using the same data adapter from the dataAdapterCache. Also, now on master, it times out before completing with `Error: timed out waiting for getRefNameMapForAdapter($conf, 'hg19')` but that could be separate issue

**Comment by cmdcolin** [comment]
I think this may still be a present problem
Click the SKBR3 (NGMLR) track, select the network tab, filter on BAI, observe that multiple copies of the BAI are downloaded (a 100MB BAI downloaded twice, 200MB transferred)

**Comment by rbuels** [comment]
yeah i see it now as well
